name: Example of simple GitHub Action

on:
  push: 
    branches: [master]

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Hello World
      run: |
        echo "Hello World!"
